CREATE TABLE `packages` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`check_by_ai` integer DEFAULT false NOT NULL,
	`is_software_package` integer DEFAULT true NOT NULL,
	`app_vendor` text NOT NULL,
	`app_name` text NOT NULL,
	`app_search_name` text NOT NULL,
	`app_version` text,
	`app_arch` text,
	`app_lang` text,
	`app_revision` text,
	`app_script_author` text,
	`app_script_date` text,
	`target_environment` text,
	`legacy_script_path` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL,
	`install_file_path` text NOT NULL,
	`install_args` text,
	`install_file_path_mst` text,
	`install_file_path_msp` text,
	`uninstall_file_path` text,
	`uninstall_args` text,
	`uninstall_type` text DEFAULT 'EXE' NOT NULL,
	`require_admin` integer,
	`success_exit_codes` text,
	`reboot_exit_codes` text,
	`processes_to_close` text,
	`processes_to_close_timer` integer DEFAULT 900,
	`pre_install_checks` text,
	`update_path` text,
	`post_install_actions` text,
	`extended_return_codes` text,
	`post_uninstall_actions` text,
	`original_script_text` text
);
